#-------------------Install and enable samba---------------

- name: Install samba on every file server
  tags: get_samba,file_servers
  package:
    name: samba
    state: latest

- name: Start and enable samba (Ubuntu)
  tags: get_samba,file_servers
  service:
    name: smbd
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Start and enable samba (Oracle Linux)
  tags: get_samba,file_servers
  service:
    name: smb
    state: started
    enabled: yes
  when: ansible_distribution == "OracleLinux"


#------------Configure Firewall to allow samba--------------

- name: Configure Firewall for samba (Ubuntu)
  tags: allow_samba,file_servers
  ufw:
    name: "Samba"
    rule: allow
  when: ansible_distribution == "Ubuntu"

- name: Configure Firewall for Samba (Oracle Linux)
  tags: allow_samba,file_servers
  firewalld:
    service: samba
    state: enabled
    permanent: yes
  when: ansible_distribution == "OracleLinux"

#----------Copy admin_manual to each node---------------------

- name: Copy admin_manual to each node
  tags: admin_manual,file_servers
  copy:
    src: admin_manual
    dest: /usr/local/bin/admin_manual
    owner: admin1
    group: admin1
    mode: 0440

#------------------------------------Download Pycharm--------------------------------

- name: Download Pycharm Community Edition to each node
  tags: get_pycharm,file_servers
  get_url:
    url: "https://download.jetbrains.com/python/pycharm-community-2021.3.1.tar.gz"
    dest: /usr/local/bin/pycharm-community-2021.3.1.tar.gz
