---
#=========================================================================PLAYS FOR WEB SERVERS===========================================================================

- hosts: web_servers
  become: true
  roles:
    - web_servers

#=====================================================================PLAYS FOR DATABASE SERVERS========================================================================

- name: Configure database servers
  hosts: db_servers
  become: yes
  roles:
    - db_servers

#=======================================================================PLAYS FOR FILE SERVERS===========================================================================

- name: File Servers
  hosts: file_servers
  become: yes
  roles:
    - file_servers

#=======================================================================ANSIBLE VAULT PLAY===============================================================================

- hosts: all
  become: true
  roles:
    - base
#========================================================================================================================================================================
