---
#=========================================================================PLAYS FOR WEB SERVERS===========================================================================

- hosts: web_servers
  become: true
  roles:
    - web_servers
    
#=====================================================================PLAYS FOR DATABASE SERVERS========================================================================

- name: Configure database servers
  hosts: db_servers
  become: yes
  tasks:
    #---------------------------Install and activate mySQL server------------------------

    - name: Install MySQL
      tags: get_mysql
      package:
        name: mysql-server
        state: latest

    - name: Start and enable MySQL on OracleLinux
      tags: get_mysql
      service:
        name: mysqld
        state: started
        enabled: yes
      when: ansible_distribution == 'OracleLinux'

    #----------------------Install Ansible requirements for mysql_user module----------------------------

    - name: Install mysql_user requirements (Ubuntu)
      tags: mysql_config
      apt:
        name:
          - python3-pip, python3-virtualenv, python3-wheel, gcc
          - python3-dev, default-libmysqlclient-dev, build-essential, pkg-config
      when: ansible_distribution == "Ubuntu"

    - name: Install mysql_user requirements (Oracle Linux)
      tags: mysql_config
      dnf:
        name:
          - python3-pip, python3-virtualenv, python3-wheel
          - python3-devel, mysql-devel, pkgconfig, gcc
      when: ansible_distribution == "OracleLinux"

    - name: Install mysqlclient python package
      tags: mysql_config
      ansible.builtin.pip:
        name: mysqlclient

    # -------------Login with default credentials and set root user password------------------------------

    - name: Set MySQL root password on Ubuntu
      tags: mysql_config
      mysql_user:
        name: root
        password: mySQLingryd
        host: localhost
        login_user: root
        login_password: ""
      when: ansible_distribution == 'Ubuntu'

    - name: Set MySQL root password on OracleLinux
      tags: mysql_config,mysql_setup
      mysql_user:
        name: root
        password: mySQLingryd
        state: present
        host: localhost
        login_user: root
        login_password: ""
      when: ansible_distribution == 'OracleLinux'

#=======================================================================PLAYS FOR FILE SERVERS===========================================================================

- name: File Servers
  hosts: file_servers
  become: yes
  tasks:
    #-------------------Install and enable samba---------------

    - name: Install samba on every file server
      tags: get_samba
      package:
        name: samba
        state: latest

    - name: Start and enable samba
      tags: get_samba
      service:
        name: samba
        state: started
        enabled: yes

    #------------Configure Firewall to allow samba--------------

    - name: Configure Firewall for samba (Ubuntu)
      tags: allow_samba
      ufw:
        name: "Samba"
        rule: allow
      when: ansible_distribution == "Ubuntu"

    - name: Configure Firewall for Samba (Oracle Linux)
      tags: allow_samba
      firewalld:
        service: samba
        permanent: yes
      when: ansible_distribution == "OracleLinux"

    #----------Copy admin_manual to each node---------------------

    - name: Copy admin_manual to each node
      tags: admin_manual
      copy:
        src: admin_manual
        dest: /usr/local/bin/admin_manual
        owner: admin1
        group: admin1
        mode: 0440

    #------------------------------------Download Pycharm--------------------------------

    - name: Download Pycharm Community Edition to each node
      tags: get_pycharm
      get_url:
        url: "https://download.jetbrains.com/python/pycharm-community-2021.3.1.tar.gz"
        dest: /usr/local/bin/pycharm-community-2021.3.1.tar.gz

#=======================================================================ANSIBLE VAULT PLAY===============================================================================---
- hosts: all
  become: true
  roles:
    - base
