--- 

- hosts: web_servers
  become: true
  pre_tasks:
     
   - name: Update cache (Ubuntu)
     apt:
      update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

   - name: Update cache (Oracle Linux)
     dnf:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "OracleLinux"

  tasks:

   - name: Install apache2 and support packages (Ubuntu)
     apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
     when: ansible_distribution == "Ubuntu"

   - name: Install apache2 and support packages (Oracle Linux)
     dnf:
      name:
        - httpd
        - php
      state: latest
     when: ansible_distribution == "OracleLinux"

   - name: Start and enable apache (Oracle Linux)
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "OracleLinux"


   - name: Change email address for Admin (Oracle Linux)
     lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: "^ServerAdmin"
       line: ServerAdmin martin.mato@ingrydacademy.com
     when: ansible_distribution == "OracleLinux"
     register: email

   - name: restart apache (Oracle Linux)
     service:
      name: httpd
      state: restarted
     when: email.changed


   - name: Change email address for Admin (Oracle Linux)
    lineinfile:
       path: /etc/apache2/sites-available/000-default.conf
       regexp: "ServerAdmin"
       line: ServerAdmin martin.mato@ingrydacademy.com
    when: ansible_distribution == "Ubuntu"
    register: apache

  - name: restart apache (Ubuntu)
    service:
      name: apache2
      state: restarted
    when: apache.changed

