--- 

- hosts: all
  become: true
  pre_tasks:
     
   - name: Update cache (Ubuntu)
     apt:
      update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

   - name: Update cache (Oracle Linux)
     dnf:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "OracleLinux"

  tasks:

   - name: Install apache2 and support packages (Ubuntu)
     apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
     when: ansible_distribution == "Ubuntu"

   - name: Install apache2 and support packages (Oracle Linux)
     dnf:
      name:
        - httpd
        - php
      state: latest
     when: ansible_distribution == "OracleLinux"

   - name: Start and enable apache (Oracle Linux)
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "OracleLinux"
