---
#=========================================================================PLAYS FOR ALL SERVERS=========================================================================

#- name: Bootstrap for all nodes
- hosts: all
  become: true
  roles:
    - base
#=========================================================================PLAYS FOR WEB SERVERS==========================================================================

#- name: Configure Web Servers
- hosts: web_servers
  become: true
  roles:
    - web_servers

#=====================================================================PLAYS FOR DATABASE SERVERS========================================================================

#- name: Configure Database Servers
- hosts: db_servers
  become: true
  roles:
    - db_servers

#=======================================================================PLAYS FOR FILE SERVERS===========================================================================

#- name: Configure File Servers
- hosts: file_servers
  become: true
  roles:
    - file_servers
