#---------------------Update Multi-distro Caches--------------------------------

- name: Update cache (Ubuntu)
  tags: update_cache,web_servers
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Update cache (Oracle Linux)
  tags: update_cache,web_servers
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "OracleLinux"

#-------------------Install apache and supporting packages-----------------------

- name: Install apache2 and support packages (Ubuntu)
  tags: get_apache,apache,web_servers
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install apache2 and support packages (Oracle Linux)
  tags: get_apache,apache,web_servers
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "OracleLinux"

#-------------------Start and enable apache(httpd) on Oracle Linux----------------

- name: Start and enable apache (Oracle Linux)
  tags: start_httpd,apache,web_servers
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "OracleLinux"

#--------------Update the ServerAdmin contact info and restart apache if successful---------------

- name: Change email address for Admin (Oracle Linux)
  tags: email_update,apache,web_servers
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin martin.mato@ingrydacademy.com
  when: ansible_distribution == "OracleLinux"
  register: email

- name: restart apache (Oracle Linux)
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == "OracleLinux" and email.changed

- name: Change email address for Admin (Ubuntu)
  tags: email_update,apache,web_servers
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: "ServerAdmin"
    line: ServerAdmin martin.mato@ingrydacademy.com
  when: ansible_distribution == "Ubuntu"
  register: apache

- name: restart apache (Ubuntu)
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Ubuntu" and apache.changed

#-------------------Configure and enable Firewalls to allow all web traffic-----------------------

- name: Configure Firewall for web_servers (Ubuntu)
  tags: allow_apache,web_servers
  ufw:
    state: enabled
    rule: allow
    name: "{{ item }}"
  with_items:
    - "Apache Full"
    - "OpenSSH"
  when: ansible_distribution == "Ubuntu"
  register: ufw

- name: Enable Firewall (Ubuntu)
  service:
    name: ufw
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu" and ufw.changed

- name: Configure Firewall for web_servers (Oracle Linux)
  tags: allow_httpd,web_servers
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - http
    - https
    - ssh
  when: ansible_distribution == "OracleLinux"
  register: firewalld

- name: Enable Firewall (Oracle Linux)
  service:
    name: firewalld
    state: restarted
    enabled: yes
  when: ansible_distribution == "OracleLinux" and firewalld.changed
